#!/bin/sh
#export
LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "username/password@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))"<<EOF
DROP TABLE "RETAIL_STORE" CASCADE CONSTRAINTS;
DROP TABLE "MANAGER" CASCADE CONSTRAINTS;
DROP TABLE "EMPLOYEE" CASCADE CONSTRAINTS;
DROP TABLE "ADMIN" CASCADE CONSTRAINTS;
DROP TABLE "TRANSACTION" CASCADE CONSTRAINTS;
DROP TABLE "PROMOTION" CASCADE CONSTRAINTS;
DROP TABLE "TAG" CASCADE CONSTRAINTS;
DROP TABLE "REWARDS_CUSTOMER" CASCADE CONSTRAINTS;
DROP TABLE "WAREHOUSE" CASCADE CONSTRAINTS;
DROP TABLE "PRODUCT" CASCADE CONSTRAINTS;
DROP TABLE "EMPLOYEE_SHIFT" CASCADE CONSTRAINTS;
DROP TABLE "EMPLOYEE_SHIFT_EMPLOYEE" CASCADE CONSTRAINTS;
DROP TABLE "WAREHOUSE_RETAIL_STORE" CASCADE CONSTRAINTS;
DROP TABLE "RETAIL_STORE_PRODUCT" CASCADE CONSTRAINTS;
DROP TABLE "WAREHOUSE_PRODUCT" CASCADE CONSTRAINTS;
DROP TABLE "TRANSACTION_PRODUCT" CASCADE CONSTRAINTS;
DROP TABLE "TRANSACTION_PROMOTION" CASCADE CONSTRAINTS;
DROP TABLE "PROMOTION_TAG" CASCADE CONSTRAINTS;
DROP TABLE "PRODUCT_TAG" CASCADE CONSTRAINTS;
exit;
EOF
